#!/bin/bash

set -eu

usage() {
    echo "USAGE"
    echo
    echo "run rm with th given arguments:"
    echo
    echo "  $0 rm <arguments>"
    echo
    echo "show the transaction log:"
    echo
    echo "  $0 log"
    echo
    echo "revert the last operation:"
    echo
    echo "  $0 revert last"
    echo
    echo "revert a particular operation:"
    echo
    echo "  $0 revert <operation ID>"
    echo
    echo "permanently clear the transactions:"
    echo
    echo "  $0 clear"
    echo
    exit 2
}

fatal() {
    echo "Error: $1"
    exit 1
}

CARELESS_PATH="${HOME}/.careless"
CARELESS_LOG="${CARELESS_PATH}/log"

careless_rm() {
    CARELESS_ID="${BASHPID}.$(date +%s)"
    export CARELESS_OPERATION_PATH="${CARELESS_PATH}/${CARELESS_ID}"

    mkdir -p "${CARELESS_OPERATION_PATH}"
    echo "${CARELESS_ID}" "$(pwd)" "rm $@" >> "${CARELESS_LOG}"

    export LD_PRELOAD="/usr/local/lib/libcareless.so"
    exec rm $@
}

careless_log() {
    if [ ! -e "${CARELESS_LOG}" ]; then
        return
    fi

    less "${CARELESS_LOG}"
}

careless_revert() {
    if [ $# -ne 1 ]; then
        usage
    fi

    CARELESS_ID="$1"

    if [ "${CARELESS_ID}" == "last" ]; then
        if [ ! -e "${CARELESS_LOG}" ]; then
            fatal "no operation to revert"
        fi

        CARELESS_ID=$(tail -1 "${CARELESS_LOG}" | cut -f1 -d\ )

        if [ -z "${CARELESS_ID}" ]; then
            fatal "no operation to revert"
        fi
    fi

    if ! egrep "^${CARELESS_ID} " "${CARELESS_LOG}" >& /dev/null; then
        fatal "unknown operation ${CARELESS_ID}"
    fi

    if [ ! -d "${CARELESS_PATH}/${CARELESS_ID}" ]; then
        fatal "no data for operation ${CARELESS_ID}"
    fi

    cp -ri ${CARELESS_PATH}/${CARELESS_ID}/* /
}

careless_clear() {
    rm -rf "${CARELESS_PATH}"/*
}

if [ $# -eq 0 ]; then
    usage
fi

command=$1
shift 1

case "$command" in
    "rm") careless_rm $@ ;;
    "log") careless_log ;;
    "revert") careless_revert $@ ;;
    "clear") careless_clear $@ ;;
    *) usage ;;
esac
